sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: KWzI9e9C3kutLg1bmObbGD/yWOqfPYylNpzMRS+mVRyiUEDtj/DuyDAWyZUfvUZgbp82CrEBYiqxK4mLXrVPJR6bXaX7y7w29hZentN0tOHjM4dU6xURsccpf2vuhumblC5CXJnWqoHPfLCyapWZ5x45mUfIzWJWss0AHzfKL/gxrMc+ofqq/zCa4aA0EKBdwyy01HaMJOQ0LKXX61FJILJoYF8m8vZetvOWZd01OrrFA1szTtz2I07nfaGE5nRBlq4LXBID+EVgo4HoHBRMwvRdB/9oWOWgDbEWeffG0Su1nuJWw5zZVdiq5cnIolnU8cQ36rzkew/kgQWMT845ZUNpCK5AygOFEP+xBg9xXND0pLrAn+1VifoldBahjh1S8J+miKIRloG1e5qlmzBi/s2aOngUFyvnWOdUZcdbDz7wXv6uJayWBkI8gd37KyDhaAtLJHoWnRFE9FGKOR3N1Tkj4P8AXA40yMqcreH9Yt9tbxlAcwIFBDN8Wd83K3ENJavHFB9UAA6vpPZahxI3LqCESKS6fBqJRRPiEHIB8/esTw7gqfq1AYOV+ilCUV5H1txK9D+S7uWrB2ekZMGjY7XsJ9G8wMAME0D23lxivT8gFppGziUalFHTZmCS+jnZ+GeLV5n9nlF5miz+i6ET2rSakqfED8++LMB+561kN5Q=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/King-Henry-VI-First-Part_1500
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy